plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - examples/**/*
    - bin/*
Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
